# Generated by Django 5.0.6 on 2024-07-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgCarrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='carousel_images/')),
                ('image2', models.ImageField(upload_to='carousel_images/')),
                ('image3', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
    ]
