# Generated by Django 5.0.6 on 2024-07-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_eletiva_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eletiva',
        ),
    ]
