# Generated by Django 5.0.6 on 2024-07-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_delete_eletiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eletivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('image', models.ImageField(upload_to='eletivas_img')),
            ],
        ),
    ]
