# Generated by Django 5.0.6 on 2024-07-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_eletivas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eletivas',
        ),
    ]
