# Generated by Django 5.0.6 on 2024-07-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0007_delete_eletivas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eletiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ele_images/')),
            ],
        ),
    ]
