# Generated by Django 5.0.6 on 2024-08-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0009_tutoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletiva',
            name='sub_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
