# Generated by Django 5.0.6 on 2024-08-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0010_eletiva_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_2',
            field=models.TextField(null=True),
        ),
    ]
