# Generated by Django 5.0.6 on 2024-08-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0012_sociallinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
