# Generated by Django 5.0.6 on 2024-09-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0014_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaisSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='mais_images/')),
                ('image_2', models.ImageField(null=True, upload_to='mais_images/')),
                ('image_3', models.ImageField(null=True, upload_to='mais_images/')),
            ],
        ),
    ]
