# Generated by Django 5.0.6 on 2024-09-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0018_nossahistoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nossahistoria',
            name='image',
            field=models.ImageField(null=True, upload_to='tutoria_images/'),
        ),
    ]
