# Generated by Django 5.0.6 on 2024-09-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0019_alter_nossahistoria_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.AddField(
            model_name='event',
            name='horario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
