# Generated by Django 5.0.6 on 2024-09-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0020_remove_event_created_at_event_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
