# Generated by Django 5.0.6 on 2024-09-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0021_delete_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
