# Generated by Django 5.0.6 on 2024-09-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0022_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_2', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='news_images/')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_2', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
