# Generated by Django 5.0.6 on 2024-10-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0024_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
