# Generated by Django 5.0.6 on 2024-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0025_alter_evento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstwo',
            name='date_published',
            field=models.TextField(null=True),
        ),
    ]
