# Generated by Django 5.0.6 on 2024-10-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0026_alter_newstwo_date_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstwo',
            old_name='date_published',
            new_name='date',
        ),
    ]
