# Generated by Django 5.0.6 on 2024-10-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0027_rename_date_published_newstwo_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsTwo',
        ),
    ]
