# Generated by Django 5.0.6 on 2024-10-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0028_delete_newstwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao1', models.TextField()),
                ('descricao2', models.TextField()),
                ('imagem', models.ImageField(upload_to='news_images/')),
                ('data_publicacao', models.DateField()),
            ],
        ),
    ]
