# Generated by Django 5.0.6 on 2024-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0029_noticia2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nossahistoria',
            name='description',
        ),
        migrations.AddField(
            model_name='nossahistoria',
            name='data_publicacao',
            field=models.DateField(null=True),
        ),
    ]
